// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	core "magicrouter/core"

	mock "github.com/stretchr/testify/mock"
)

// BreakerService is an autogenerated mock type for the BreakerService type
type BreakerService struct {
	mock.Mock
}

// GetState provides a mock function with given fields: breakerID
func (_m *BreakerService) GetState(breakerID string) core.BreakerState {
	ret := _m.Called(breakerID)

	var r0 core.BreakerState
	if rf, ok := ret.Get(0).(func(string) core.BreakerState); ok {
		r0 = rf(breakerID)
	} else {
		r0 = ret.Get(0).(core.BreakerState)
	}

	return r0
}

// ReportFailure provides a mock function with given fields: breakerID
func (_m *BreakerService) ReportFailure(breakerID string) {
	_m.Called(breakerID)
}

// ReportSuccess provides a mock function with given fields: breakerID
func (_m *BreakerService) ReportSuccess(breakerID string) {
	_m.Called(breakerID)
}

// NewBreakerService creates a new instance of BreakerService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBreakerService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BreakerService {
	mock := &BreakerService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
