// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TokenResolver is an autogenerated mock type for the TokenResolver type
type TokenResolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: apiToken
func (_m *TokenResolver) Resolve(apiToken string) (string, error) {
	ret := _m.Called(apiToken)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(apiToken)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(apiToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(apiToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTokenResolver creates a new instance of TokenResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenResolver {
	mock := &TokenResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
